### ISSUE TITLE
Color settings don't save

### ISSUE THREAD

**Issue by diggtrap** [neropatti/ammo-percentage-indicator#10]
Everything works fine so far, but after changing the colors, they just reset when modhub closes.

https://files.catbox.moe/y9rf3y.gif

**Comment by Spiderfreak** [comment]
I second this issue, is this actively being worked on to solve or was this mod forgotten about?

**Comment by neropatti** [comment]
The extended version has been abandoned. Sorry for the inconvenience & late reply. If anyone wants to contribute to the extended version, get in contact with me!
