### ISSUE TITLE
This mod has not been updated to the current version of the game

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [neropatti/ammo-percentage-indicator#12]
Hi folks,

I really enjoy this mod, unfornuately it is currently shown on the modding UI with a warning saying "This mod has not been updated to the current version of the game".

I think this prevents the mod from being autoloaded on game startup.
Is it fixable ?

**Comment by neropatti** [comment]
Whoops, I have not taken a look at the issues page in a long time. This should no longer be an issue, though. Let me know if anything else comes up!
