### ISSUE TITLE
Mod hub settings

### ISSUE THREAD

**Issue by C0R-PSE** [neropatti/ammo-percentage-indicator#9]
There aren't such options as Integrated^2 or Integrated high (with or without other mods)

**Comment by ghost** [comment]
Recently deprected settings. Trying to get a list like system for the % #8 working. Will probably circle back to it.

**Comment by neropatti** [comment]
The extended version has been abandoned, and the base version won't be getting any settings. Sorry for the inconvenience & late reply.

**Comment by neropatti** [comment]
Whoop, meant to close this issue with that last comment :b
